// Generates src/ui/icons.js: the Solar (linear) icons the UI uses, inlined as SVG bodies, so the app needs no
// icon font or network request. Add a name to NAMES and run: node tools/icons/build-icons.mjs
// Solar has no hand icon; HAND is drawn in the same style (24 grid, 1.5 stroke, round caps and joins).
import {readFileSync,writeFileSync} from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const set=JSON.parse(readFileSync(require.resolve('@iconify-json/solar/icons.json'),'utf8'));
const NAMES=`cursor move restart planet smartphone tablet laptop monitor window-frame display gallery-wide widget sun-2 lightbulb
sun-fog sun gallery-add gallery frame target maximize-square play hamburger-menu alt-arrow-down alt-arrow-right alt-arrow-up undo-left
undo-right add-circle minus-circle eye eye-closed menu-dots refresh link trash-bin-minimalistic copy layers-minimalistic layers
align-vertical-center align-horizontal-center align-bottom upload-minimalistic global camera settings folder-open diskette
download-minimalistic close-circle magnifer export import moon double-alt-arrow-up double-alt-arrow-down arrow-up arrow-down
info-circle magic-stick-3 lamp pallete-2 ruler keyboard close-square pause rewind-back repeat video-frame-play-horizontal`.split(/\s+/).filter(Boolean);
const S='fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"';
const HAND='<path '+S+' d="M8 13.5V6a1.5 1.5 0 0 1 3 0v5M11 11V4.5a1.5 1.5 0 0 1 3 0V11m0-.5V6a1.5 1.5 0 0 1 3 0v5.5m0-2a1.5 1.5 0 0 1 3 0V14c0 4.14-3.13 7.5-7 7.5h-.7c-2.3 0-3.8-.8-5.3-2.5l-3.6-4.1a1.6 1.6 0 0 1 2.4-2.1L8 15"/>';
const out={hand:HAND};
for(const n of NAMES){const k=n+'-linear',ic=set.icons[k]||set.icons[(set.aliases[k]||{}).parent];if(!ic)throw new Error('Solar icon not found: '+k);out[n]=ic.body;}
const src=`/* Generated by tools/icons/build-icons.mjs from @iconify-json/solar (linear style, CC BY 4.0, 480 Design).
   Do not edit by hand. */
const ICONS=${JSON.stringify(out,null,0).replace(/","/g,'",\n"')};
// icon('name') -> inline SVG string (16 px unless a size is given); decorative, the button carries the label
function icon(name,size){const b=ICONS[name];if(!b)return '';const s=size||16;
  return '<svg class="ic" width="'+s+'" height="'+s+'" viewBox="0 0 24 24" aria-hidden="true" focusable="false">'+b+'</svg>';}
// replaces the content of every [data-icon] element under root with its icon (data-size optional)
function hydrateIcons(root){(root||document).querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=icon(el.dataset.icon,+el.dataset.size||0);});}

export {ICONS,hydrateIcons,icon};
`;
writeFileSync(new URL('../../src/ui/icons.js',import.meta.url),src);
console.log('icons:',Object.keys(out).length);
